In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  5 07:35:05 2018

@author: Nelson
"""

import numpy as np

a = np.array( [30,20,40,50] )
b = np.arange( 4 )

# Basic operations

print(a-b)
print(b**2)
print(a*b)

print(np.sin(a))

print(a<30)

print(sum(a))
print(a.sum())
print(min(a))
print(a.min())

print(a.max())
print(a.mean())
a.sort()
print(a)
print(a.cumsum())
print(a.cumprod())
print(a.repeat(2))
c = np.array( [3.17,2.33,4.25,5] )
print(c.round(1))

s = np.array( [1703996] )
print(list(map(hex,s)))
s.byteswap(inplace=True)
print(list(map(hex,s)))




# Universal functions

print(np.exp(a))
print(np.sqrt(b))
print(np.add(a,b))


# Operations by axes

c = np.arange(12).reshape(3,4)
print(c)


print(c.sum(axis=0))
print(c.sum(axis=1))
print(c.min(axis=0))
print(c.max(axis=1))

[30 19 38 47]
[0 1 4 9]
[  0  20  80 150]
[-0.98803162  0.91294525  0.74511316 -0.26237485]
[False  True False False]
140
140
20
20
50
35.0
[20 30 40 50]
[ 20  50  90 140]
[     20     600   24000 1200000]
[20 20 30 30 40 40 50 50]
[3.2 2.3 4.2 5. ]
['0x1a003c']
['0x3c001a0000000000']
[4.85165195e+08 1.06864746e+13 2.35385267e+17 5.18470553e+21]
[0.         1.         1.41421356 1.73205081]
[20 31 42 53]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]
[0 1 2 3]
[ 3  7 11]

#TITULO