In [0]:
import numpy as np
import pandas as pd

a = np.random.randint(low=0, high=10, size=(3, 3))
df = pd.DataFrame(data=a,columns=['A', 'B', 'C'])
                  
def funcion1(df,colum):
  df[colum]=0
  return df[colum] 

funcion1(df,3)
print(df)

In [0]:
import pandas as pd

# CONCATENACIÓN VERTICAL

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],'B': ['B0', 'B1', 'B2', 'B3'],
'C': ['C0', 'C1', 'C2', 'C3'],'D': ['D0', 'D1', 'D2', 'D3']},index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],'B': ['B4', 'B5', 'B6', 'B7'],
'C': ['C4', 'C5', 'C6', 'C7'],'D': ['D4', 'D5', 'D6', 'D7']},index=[4, 5, 6, 7])

frames=[df1,df2]
dfv=pd.concat(frames, axis=0) # axis=0 por defecto
print(df1)
print(df2)
print(dfv)

# CONCATENACIÓN HORIZONTAL

df3 = pd.DataFrame({'E': ['E0', 'E1', 'E2', 'E3'],'F': ['F0', 'F1', 'F2', 'F3'],
'G': ['G0', 'G1', 'G2', 'G3'],'H': ['H0', 'H1', 'H2', 'H3']},index=[0, 1, 2, 3])

frames=[df1,df3]
dfh=pd.concat(frames, axis=1)
print(df1)
print(df3)
print(dfh)

# INNER Y OUTER

df4 = pd.DataFrame({'A': ['A2', 'A3', 'A6', 'A7'],'C': ['C2', 'C3', 'C6', 'C7'],
'G': ['G2', 'G3', 'C6', 'C7'],'H': ['H2', 'H2', 'D6', 'D7']},index=[2, 3, 6, 7])


frames=[df1,df4]
dfv=pd.concat(frames, axis=0, join='outer') #join='outer' por defecto
print(df1)
print(df4)
print(dfv)#solo coincide las columnas lo demas nan

dfh=pd.concat(frames, axis=1, join='outer') #join='outer' por defecto
print(df1)
print(df4)
print(dfh)#solo coincide las filas

frames=[df1,df4]
dfv=pd.concat(frames, axis=0, join='inner')
print(df1)
print(df4)
print(dfv)#solo coincide las columnas lo demas se borra

dfh=pd.concat(frames, axis=1, join='inner') 
print(df1)
print(df4)
print(dfh)#solo coincide las filas y lo demas se borra

# EXACT INDEX / EXACT COLUMNS

dfh = pd.concat([df1, df4], axis=1, join_axes=[df1.index])
print(df1)
print(df4)
print(dfh)#lo obligas a mantener los datos de la fila del frame 1

dfv = pd.concat([df1, df4], axis=0, join_axes=[df1.columns])
print(df1)
print(df4)
print(dfv)#lo obligas a mantener los datos de la columna del frame 1

# IGNORE INDEX

dfV = pd.concat([df1, df4], axis=0, ignore_index = True)
print(df1)
print(df4)
print(dfV)

#IGNORE COLUMN

dfh = pd.concat([df1, df4], axis=1, ignore_index = True)
print(df1)
print(df4)
print(dfh)

# CONCATENANDO CON APPEND

dfv=df1.append(df4)
print(df1)
print(df4)
print(dfv)

dfv=df1.append(df4, ignore_index=True)
print(df1)
print(df4)
print(dfv)

In [0]:
import numpy as np
import pandas as pd

a = np.random.randint(low=0, high=10, size=(5, 3))
df = pd.DataFrame(data=a, columns=['A', 'B', 'C'])

# PIPE -> permite aplicar funciones de forma encadenada que reciban y retornen dataframes 


# Creamos las funciones
def funcion1(dataframe):
    return dataframe.abs()

def funcion2(dataframe, col):
    # col = (col^2 + col)^(1/2)
    dataframe[col] = np.sqrt(dataframe[col]**2 + dataframe[col])
    return dataframe


# Creamos el pipe con las funciones anteriores
print(df.pipe(funcion1).pipe(funcion2, 'A'))

# APPLY -> permite aplicar funciones a dataframes, ya sean funciones existentes o definidas por el programador

# función ya existente
print(df.apply(np.mean))
print(df.apply(np.mean, axis=1))

# función definida
print(df.apply(lambda x: x.max() - x.min()))
print(df.apply(lambda x: x.max() - x.min(), axis=1))

# AGG-> Crea un nuevo dataframe con una fila por cada función aplicada a cada una de las columnas de un dataframe de entrada

print(df.agg(['sum', 'mean']))

print(df.agg([np.sum, 'mean']))

# TRANSFORM-> Crea un nuevo dataframe con los datos resultantes de aplicar una o varias funciones a cada uno de los elementos de un dataframe de entrada

print(df.transform([np.abs, lambda x: x+1]))

# APPLYMAP> Permite aplicar a un dataframe una función que recibe y retorna un único valor

f = lambda x: len(str(x/1000))
print(df.applymap(f))

In [0]:
import pandas as pd

docentes = pd.read_csv('Docentes_De_Planta.csv')

docentes.iloc[:,3]
docentes.loc[:, ['doctorado', 'pregrado']]

docentes_nan = docentes.isnull()
#crea una matriz y muestra true donde hay Nan

docentes_sin_nan1 = docentes.dropna(axis=1, how='any')
#borra columnas que tengan algun Nan , 0 filas

docentes_sin_nan2 = docentes.dropna(axis=1, how='all')
#borra columnas que tengan todo Nan

docentes_nuevo = docentes.fillna(value=3)
#llena los Nan con 3

docentes_nuevo = docentes.fillna(docentes.mean())
#lo llena con la media

docentes_nuevo = docentes.fillna(method='bfill', limit=1)
#replica el valor siguiente al Nan(method) ,pero solo el primero de la columna(limit)

docentes['DOCTORADO'] >= 5
#devuelve la columna doctorado con true si es mayor o igual a 5
                                                   
docentes[docentes['DOCTORADO'] >= 5]
#indica el index y devuelve un dataframe
#toma la columna doctorado y quita las filas que sean menores a 5
#los nan que estan en doctorado los toma como menor a 5

docentes['MT'][docentes['DOCTORADO'] >= 5]
#hace lo anterior pero solo muestra la columna MT
#no importa si la columna MT tiene nan los deja

docentes[(docentes['DOCTORADO'] >= 5) & (docentes['MAESTRÍA'] >= 7)]
#indica el index y devuelve un dataframe
#toma la columna doctorado y luego toma la culumna maestria
# y quita las filas que en doctorado sea menor a 5 y en maestria menor a 7
#los nan que estan en doctorado y mestria los toma como false

#tecnicas de filtrado
Where
#filter1 = docentes["doctorado"]==5
#docentes.where(filter, inplace = True)
#retorna el dataframe
#en la fila llamada doctorado si es igual a 5 se muestra y los
#que no cumplen se rellena con nan 

Mask
#reemplazar todos los valores mayores que 10 con -25
#docentes.mask(docentes > 10, -25) 

Isin
#es verdadero siempre que en la fila team este escrito ingeiero o financiero
#new = datos["team"].isin(["ingeniero, financiero"]) 
#retorna un dataframe donde dio verdadero

Query
#docentes.query('doctorado' == True', inplace = True) 
#toda la fila de doctorado se vulve true
#si los nombres de las columnas tienen espacios vacíos
#, los espacios en los nombres de las columnas se reemplazan con '_'

Eval
#suma esa fila y el resultado lo agrega al frente generando una columna nueva
#si en la fila hay un nan el resultado de esa columna nueva sera nan

In [0]:
import pandas as pd

docentes = pd.read_csv('mnist_test.csv')